### ISSUE TITLE
BB order not working for spark sim as intended

### ISSUE THREAD

**Issue by bluelanturn** [BluuArc/bf-mt#8] opened 2019-05-28 06:04 UTC
The BB order for the spark sim is not working as intended 
Spark Sim Input:
![image](https://user-images.githubusercontent.com/51024827/58454436-cc3ef680-8161-11e9-9dbc-95a295c62fec.png)
Spark Sim Output:
![image](https://user-images.githubusercontent.com/51024827/58454486-f1cc0000-8161-11e9-8582-7a46cd0e0839.png)
as highlighted Saerenthis should have his sbb used last but after the sim it doesn't

**Comment by BluuArc** [comment] 2019-05-28 12:17
I [pushed a fix](https://github.com/BluuArc/bf-mt/commit/eeb92153a0a88b36fdc80db802972b594b0e2f23) that should've addressed the issue. Can you verify that the issue is fixed on your end?

**Comment by bluelanturn** [comment] 2019-05-28 22:51
Fixed 👍

**Closed** 2019-05-28 22:52 UTC
Labels: bug
